name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: chbrandt
          config_timezone: Europe/Berlin
          template: classic
          
          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_activity: yes
          plugin_activity_visibility: all
          plugin_activity_skipped: chbrandt/chbrandt
          plugin_licenses: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_sort: activity
          
