name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: chbrandt
          config_timezone: Europe/Berlin
          template: classic
          
          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: linguist-vendored
          plugin_licenses: yes
          #plugin_stackoverflow: yes
          #plugin_stackoverflow_sections: answers-top,answers-recent
          #plugin_stackoverflow_user: 687896
          #plugin_topics: yes
          #plugin_topics_mode: icons
          #plugin_topics_sort: activity
          
